# file for config the bot 
bot_config:
  # config for notifing new music by Discord
  discord:
    # the notif by discord actif or not ?
    # true  = actif
    # false = not actif
    actif?: true
    # if is actif config :
    #
    # for create and get token Bot (list of link for tuto)
    # https://www.writebots.com/discord-bot-token/
    # https://www.getdroidtips.com/discord-bot-token/
    # https://www.getdroidtips.com/discord-bot-token/
    # and invite in you private channel
    token: ""
    # for send in you private message get your id
    # https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID
    id: ""
  # config for notifing new music by email
  email:
    # the notif by discord actif or not ?
    # true  = actif
    # false = not actif
    actif?: false
    # if is actif config :
    #
    # protocol for send email
    # protocol list : SMTP, POP3, IMAP
    protocol: ""
    # protocol config
    protocol_config: ""
    #
  # config for notifing new music by telegram
  telegram:
    # the notif by discord actif or not ?
    # true  = actif
    # false = not actif
    actif?: false
    # if is actif config :
    #
config_navigator:
  # for must privacy for the scraping i dev the scraping with libreWolf navigator
  # so for the module "selenium-webdriver" it's necessary to declare the executable path of librewolf
  # so install librewolf (https://librewolf.net/)
  # and geckodriver, it's a driver for connecte code to firefox or firefox based navigator
  # https://github.com/mozilla/geckodriver/releases
  #
  # librewolf executable path
  libreWolf_path: "/usr/bin/librewolf"